config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'projects#index'

  get '/sign_up', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :projects
  resources :tickets
  resources :tags, except: :show
  resources :users, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets

  validates :name, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :ticket_tags
  has_many :tickets, through: :ticket_tags

  validates :name, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project

  has_many :ticket_tags
  has_many :tags, through: :ticket_tags

  validates :name, presence: true
end

app/models/ticket_tag.rb
class TicketTag < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = 'You must be logged in to do that.'
      redirect_back fallback_location: :root_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Project was successfully created.'
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Project was successfully updated.'
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = 'Project was successfully destroyed.'

    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(email: params[:email]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Welcome back!'
      redirect_to projects_path
    else
      flash[:error] = 'You could not be logged in.'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have been logged out.'
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_user, except: :index
  before_action :set_tag, only: [:edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      flash[:notice] = 'Tag was successfully created.'
      redirect_to tags_path
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      flash[:notice] = 'Tag was successfully updated.'
      redirect_to tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    flash[:notice] = 'Tag was successfully destroyed.'
    redirect_to tags_path
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      flash[:notice] = 'Ticket was successfully created.'
      redirect_to ticket_path(@ticket)
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = 'Ticket was successfully updated.'
      redirect_to ticket_path(@ticket)
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = 'Ticket was successfully destroyed.'

    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:project_id, :name, :body, :status, tag_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome to the ticketing system.'
      redirect_to projects_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :p, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav>
  <strong>Ticketing</strong>
  <%= link_to 'Projects', projects_path %>
  <%= link_to 'Tickets', tickets_path %>
  <%= link_to 'Tags', tags_path %>

  <% if logged_in? %>
    <span id ='logout'>
      Signed in as <%= current_user.name %>
      <%= link_to 'Logout', logout_path %>
    </span>
  <% else %>
    <span id='login_or_sign_up'>
      <%= link_to 'Login', login_path %>
      or
      <%= link_to 'Sign up', sign_up_path %>
    </span>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= render 'shared/errors', obj: @project %>

<%= form_for @project do |f| %>
  <dl>
    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>

    <dt><%= f.label :description %></dt>
    <dd><%= f.text_area :description %></dd>
  </dl>

  <%= f.submit %>
<% end %>

app/views/projects/_project.html.erb
<tr>
  <td>
    <strong><%= link_to project.name, project_path(project) %></strong>
    <br />
    <%= project.description %>
  </td>
  <td><%= project.tickets.count %></td>
  <td><%= project.tickets.count %></td>
</tr>

app/views/projects/edit.html.erb
<%= render 'shared/content_title', title: 'Editing Project' %>

<%= render 'form' %>

<p>
  <%= link_to 'Show', project_path(@project) %>
  |
  <%= link_to 'Back', projects_path %>
</p>

app/views/projects/index.html.erb
<%= render 'shared/content_title', title: 'Projects' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Open Tickets</th>
      <th>Total Tickets</th>
    <tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <%= render 'project', project: project %>
    <% end %>
  </tbody>
</table>

<br />
<br />

<p><%= link_to 'New Project', new_project_path %></p>

app/views/projects/new.html.erb
<%= render 'shared/content_title', title: 'New Project' %>

<%= render 'form' %>

<p><%= link_to 'Back', projects_path %></p>

app/views/projects/show.html.erb
<%= render 'shared/content_title', title: @project.name %>

<p><%= @project.description %></p>

<p>
  <%= link_to 'Edit', edit_project_path(@project) %>
  <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<h2>Tickets</h2>

<%= render 'tickets/tickets_table', tickets: @project.tickets %>

app/views/shared/_content_title.html.erb
<h1><%= title %></h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h4><%= obj.errors.count %> error prohibited this action from being completed:</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tags/_form.html.erb
<%= render 'shared/errors', obj: @tag %>

<%= form_for @tag do |f| %>
  <dl>
    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>
  </dl>

  <%= f.submit %>
<% end %>

app/views/tags/_tag.html.erb
<tr>
  <td><%= tag.name %>
  <td><%= tag.ticket_tags.count %></td>
  <td>
    <%= link_to 'Edit', edit_tag_path(tag) %>
    or
    <%= link_to 'Destroy', data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/tags/_tag_row.html.erb
<tr>
  <td><%= tag.name %>
  <td><%= tag.ticket_tags.count %></td>
  <td>
    <%= link_to 'Edit', edit_tag_path(tag) %>
    or
    <%= link_to 'Destroy', tag_path(tag), method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/tags/edit.html.erb
<%= render 'shared/content_title', title: 'Editing Tag' %>

<%= render 'form' %>

app/views/tags/index.html.erb
<%= render 'shared/content_title', title: 'Tags' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tickets</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <%= render 'tag_row', tag: tag %>
    <% end %>
  </tbody>
</table>

<br />
<br />

<p><%= link_to 'New Tag', new_tag_path %></p>

app/views/tags/new.html.erb
<%= render 'shared/content_title', title: 'New Tag' %>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tickets/_form.html.erb
<%= render 'shared/errors', obj: @ticket %>

<%= form_for @ticket do |f| %>
  <dl>
    <dt><%= f.label :project_id %></dt>
    <dd><%= f.collection_select :project_id, Project.all, :id, :name %></dd>

    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>

    <dt><%= f.label :body %></dt>
    <dd><%= f.text_area :body %></dd>

    <dt><%= f.label :status %></dt>
    <dd><%= f.select :status, ['new', 'blocked', 'in_progress', 'fixed'] %></dd>

    <dt><%= f.label 'Tags' %></dt>
    <dd><%= f.collection_select :tag_ids, Tag.all, :id, :name, {}, { multiple: true, size: 5 } %></dd>
  </dl>

  <%= f.submit %>
<% end %>

app/views/tickets/_ticket_row.html.erb
<tr>
  <td><%= link_to ticket.name, ticket_path(ticket) %></td>
  <td>Tom</td>
  <td><%= ticket.status %></td>
  <td><%= ticket.tags.map(&:name).join(', ') %></td>
  <td>
    <%= link_to 'Edit', edit_ticket_path(ticket) %>
    <%= link_to 'Destroy', ticket_path(ticket), method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/tickets/_tickets_table.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Assignee</th>
      <th>Status</th>
      <th>Tags</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <%= render 'tickets/ticket_row', ticket: ticket %>
    <% end %>
  </tbody>
</table>

app/views/tickets/edit.html.erb
<%= render 'shared/content_title', title: 'Editing Ticket' %>

<%= render 'form' %>

app/views/tickets/index.html.erb
<%= render 'shared/content_title', title: 'Tickets' %>

<%= render 'tickets_table', tickets: @tickets %>

<br />
<br />

<p><%= link_to 'New Ticket', new_ticket_path %></p>

app/views/tickets/new.html.erb
<%= render 'shared/content_title', title: 'New Ticket' %>

<%= render 'form' %>

app/views/tickets/show.html.erb
<%= render 'shared/content_title', title: @ticket.name %>

<p><%= @ticket.body %></p>

<p><strong>Tags: </strong><%= @ticket.tags.map(&:name).join(', ') %></p>

<br />

<p><%= link_to 'Edit', edit_ticket_path(@ticket) %></p>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Creator</th>
      <th>Assignee</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @ticket.status %></td>
      <td>Some guy</td>
      <td>Some gal</td>
    </tr>
  </tbody>
</table>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>

<%= render 'shared/content_title', title: 'Sign Up' %>

<%= form_for @user do |f| %>
  <dl>
    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>

    <dt><%= f.label :email %></dt>
    <dd><%= f.email_field :email %></dd>

    <dt><%= f.label :password %></dt>
    <dd><%= f.password_field :password %></dd>

    <dt><%= f.label :password_confirmation %></dt>
    <dd><%= f.password_field :password_confirmation %></dd>
  </dl>

  <%= f.submit 'Create Account' %>
<% end %>